--- #task 1 by faizan
- hosts: all
  user: faizii
  become: yes
  connection: ssh
  tasks:
    - name: installing docker 
      yum:
        name: docker
        state: present
    - name: starting services
      service:
        name: docker
        state: started
